[
  {
    Architecture: 'x86_64',
    BlockDeviceMappings: [ [Object] ],
    ClientToken: '721fbfa1-b810-4309-bd23-cd718e8d19fa',
    EbsOptimized: false,
    EnaSupport: true,
    Hypervisor: 'xen',
    NetworkInterfaces: [ [Object] ],
    RootDeviceName: '/dev/xvda',
    RootDeviceType: 'ebs',
    SecurityGroups: [ [Object] ],
    SourceDestCheck: true,
    Tags: [ [Object] ],
    VirtualizationType: 'hvm',
    CpuOptions: { CoreCount: 1, ThreadsPerCore: 1 },
    CapacityReservationSpecification: { CapacityReservationPreference: 'open' },
    HibernationOptions: { Configured: false },
    MetadataOptions: {
      State: 'applied',
      HttpTokens: 'required',
      HttpPutResponseHopLimit: 2,
      HttpEndpoint: 'enabled',
      HttpProtocolIpv6: 'disabled',
      InstanceMetadataTags: 'disabled'
    },
    EnclaveOptions: { Enabled: false },
    BootMode: 'uefi-preferred',
    PlatformDetails: 'Linux/UNIX',
    UsageOperation: 'RunInstances',
    UsageOperationUpdateTime: 2025-05-21T15:06:40.000Z,
    PrivateDnsNameOptions: {
      HostnameType: 'ip-name',
      EnableResourceNameDnsARecord: true,
      EnableResourceNameDnsAAAARecord: false
    },
    MaintenanceOptions: { AutoRecovery: 'default' },
    CurrentInstanceBootMode: 'legacy-bios',
    NetworkPerformanceOptions: { BandwidthWeighting: 'default' },
    Operator: { Managed: false },
    InstanceId: 'i-0d0415734a474f0c0',
    ImageId: 'ami-07706bb32254a7fe5',
    State: { Code: 16, Name: 'running' },
    PrivateDnsName: 'ip-172-31-2-181.us-west-1.compute.internal',
    PublicDnsName: 'ec2-54-215-198-7.us-west-1.compute.amazonaws.com',
    StateTransitionReason: '',
    AmiLaunchIndex: 0,
    ProductCodes: [],
    InstanceType: 't2.micro',
    LaunchTime: 2025-05-21T15:06:40.000Z,
    Placement: {
      GroupName: '',
      Tenancy: 'default',
      AvailabilityZone: 'us-west-1c'
    },
    Monitoring: { State: 'disabled' },
    SubnetId: 'subnet-045d90cc0c7dea920',
    VpcId: 'vpc-0a30a7888d2eb0d17',
    PrivateIpAddress: '172.31.2.181',
    PublicIpAddress: '54.215.198.7'
  },
  {
    Architecture: 'x86_64',
    BlockDeviceMappings: [ [Object] ],
    ClientToken: '721fbfa1-b810-4309-bd23-cd718e8d19fa',
    EbsOptimized: false,
    EnaSupport: true,
    Hypervisor: 'xen',
    NetworkInterfaces: [ [Object] ],
    RootDeviceName: '/dev/xvda',
    RootDeviceType: 'ebs',
    SecurityGroups: [ [Object] ],
    SourceDestCheck: true,
    Tags: [ [Object] ],
    VirtualizationType: 'hvm',
    CpuOptions: { CoreCount: 1, ThreadsPerCore: 1 },
    CapacityReservationSpecification: { CapacityReservationPreference: 'open' },
    HibernationOptions: { Configured: false },
    MetadataOptions: {
      State: 'applied',
      HttpTokens: 'required',
      HttpPutResponseHopLimit: 2,
      HttpEndpoint: 'enabled',
      HttpProtocolIpv6: 'disabled',
      InstanceMetadataTags: 'disabled'
    },
    EnclaveOptions: { Enabled: false },
    BootMode: 'uefi-preferred',
    PlatformDetails: 'Linux/UNIX',
    UsageOperation: 'RunInstances',
    UsageOperationUpdateTime: 2025-05-21T15:06:40.000Z,
    PrivateDnsNameOptions: {
      HostnameType: 'ip-name',
      EnableResourceNameDnsARecord: true,
      EnableResourceNameDnsAAAARecord: false
    },
    MaintenanceOptions: { AutoRecovery: 'default' },
    CurrentInstanceBootMode: 'legacy-bios',
    NetworkPerformanceOptions: { BandwidthWeighting: 'default' },
    Operator: { Managed: false },
    InstanceId: 'i-082dfd7d331d68492',
    ImageId: 'ami-07706bb32254a7fe5',
    State: { Code: 16, Name: 'running' },
    PrivateDnsName: 'ip-172-31-4-103.us-west-1.compute.internal',
    PublicDnsName: 'ec2-18-144-168-43.us-west-1.compute.amazonaws.com',
    StateTransitionReason: '',
    AmiLaunchIndex: 1,
    ProductCodes: [],
    InstanceType: 't2.micro',
    LaunchTime: 2025-05-21T15:06:40.000Z,
    Placement: {
      GroupName: '',
      Tenancy: 'default',
      AvailabilityZone: 'us-west-1c'
    },
    Monitoring: { State: 'disabled' },
    SubnetId: 'subnet-045d90cc0c7dea920',
    VpcId: 'vpc-0a30a7888d2eb0d17',
    PrivateIpAddress: '172.31.4.103',
    PublicIpAddress: '18.144.168.43'
  },
  {
    Architecture: 'x86_64',
    BlockDeviceMappings: [ [Object] ],
    ClientToken: '721fbfa1-b810-4309-bd23-cd718e8d19fa',
    EbsOptimized: false,
    EnaSupport: true,
    Hypervisor: 'xen',
    NetworkInterfaces: [ [Object] ],
    RootDeviceName: '/dev/xvda',
    RootDeviceType: 'ebs',
    SecurityGroups: [ [Object] ],
    SourceDestCheck: true,
    Tags: [ [Object] ],
    VirtualizationType: 'hvm',
    CpuOptions: { CoreCount: 1, ThreadsPerCore: 1 },
    CapacityReservationSpecification: { CapacityReservationPreference: 'open' },
    HibernationOptions: { Configured: false },
    MetadataOptions: {
      State: 'applied',
      HttpTokens: 'required',
      HttpPutResponseHopLimit: 2,
      HttpEndpoint: 'enabled',
      HttpProtocolIpv6: 'disabled',
      InstanceMetadataTags: 'disabled'
    },
    EnclaveOptions: { Enabled: false },
    BootMode: 'uefi-preferred',
    PlatformDetails: 'Linux/UNIX',
    UsageOperation: 'RunInstances',
    UsageOperationUpdateTime: 2025-05-21T15:06:40.000Z,
    PrivateDnsNameOptions: {
      HostnameType: 'ip-name',
      EnableResourceNameDnsARecord: true,
      EnableResourceNameDnsAAAARecord: false
    },
    MaintenanceOptions: { AutoRecovery: 'default' },
    CurrentInstanceBootMode: 'legacy-bios',
    NetworkPerformanceOptions: { BandwidthWeighting: 'default' },
    Operator: { Managed: false },
    InstanceId: 'i-00df2f423731a9178',
    ImageId: 'ami-07706bb32254a7fe5',
    State: { Code: 16, Name: 'running' },
    PrivateDnsName: 'ip-172-31-0-73.us-west-1.compute.internal',
    PublicDnsName: 'ec2-54-183-193-84.us-west-1.compute.amazonaws.com',
    StateTransitionReason: '',
    AmiLaunchIndex: 2,
    ProductCodes: [],
    InstanceType: 't2.micro',
    LaunchTime: 2025-05-21T15:06:40.000Z,
    Placement: {
      GroupName: '',
      Tenancy: 'default',
      AvailabilityZone: 'us-west-1c'
    },
    Monitoring: { State: 'disabled' },
    SubnetId: 'subnet-045d90cc0c7dea920',
    VpcId: 'vpc-0a30a7888d2eb0d17',
    PrivateIpAddress: '172.31.0.73',
    PublicIpAddress: '54.183.193.84'
  }
]